### ISSUE TITLE
Succesful Build procedure

### ISSUE THREAD

**Issue by TitouanTyack** [Unsigned-Long/RIs-Calib#1]
Hi,

I succesfully built RIs-Calib, after encountering several issues.
So, to share the information of the build procedure that worked in my case on a fresh 20.04 ubuntu install was:
- Install ros1 noetic
- build from source ceres version 2.2.0
- build from source Pangolin version 0.9.2:
In ./scripts/install_prerequisites.sh, remove all ‘catch2’  (cf https://github.com/stevenlovegrove/Pangolin/issues/913) i don’t run tests
./scripts/install_prerequisites.sh -m apt all
Built with cmake (not ninja), did not run python make
- build from source Sohpus version 1.22.10 with SOPHUS_USE_BASIC_LOGGING=ON
- build from source magic-enum
- build from source spdlog version 1.14.1 (So i did not do sudo apt-get install libspdlog-dev)
- sudo apt-get install libcereal-dev
- sudo apt-get install libyaml-cpp-dev
- clone repos
- rosdep install --from-paths src --ignore-src -r -y
- catkin_make -DCATKIN_WHITELIST_PACKAGES="ainstein_radar;ti_mmwave_rospkg;serial;sbg_driver"
- catkin_make -DCATKIN_WHITELIST_PACKAGES="ainstein_radar_msgs"
- catkin_make -DCATKIN_WHITELIST_PACKAGES="ris_calib"

**Comment by Unsigned-Long** [comment]
Thanks for sharing! 👍  As a multi-IMU multi-radar spatiotemporal calibrator, `RIs-Calib`'s existing modules have been fully integrated into `iKalibr`. So if possible, using `iKalibr` is a better choice (some small tricks have been added for radar initialization to better recover the initial values ​​of parameters).  

`iKalibr`: [https://github.com/Unsigned-Long/iKalibr.git](https://github.com/Unsigned-Long/iKalibr.git)

Tips: Maybe `iKalibr` is not easy to compile, hahaha 😃 , but I feel that the environment that `ikalibr` depends on is similar to `RIs-Calib`. So if `RIS-Calib` is compiled successfully, you can probably try to compile `iKalibr` again :muscle:.

**Comment by TitouanTyack** [comment]
Thank you for your answer.

Yes, I'll try again to compile iKalibr at some point, but for now I only need the radar-IMU calibration.
I think it will work by compiling colmap from source.

It could be great to propose your work with a Pangolin free implementation, it would makes it way easier to dockerize.
Also, I look forward to see a ros2 release ;)

I tried RIs-calib with real data using an ellipse-N sbg IMU and an AWR1843 and it looks like it works great, I have similar results usings several records.

Thanks again
